/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisaRouteImport } from './routes/_authenticated.visa'
import { Route as AuthenticatedUniversitiesRouteImport } from './routes/_authenticated.universities'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedScholarshipsRouteImport } from './routes/_authenticated.scholarships'
import { Route as AuthenticatedProfessorsRouteImport } from './routes/_authenticated.professors'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedMissionRouteImport } from './routes/_authenticated.mission'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated.mentor'
import { Route as AuthenticatedIeltsRouteImport } from './routes/_authenticated.ielts'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated.finances'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDepartureRouteImport } from './routes/_authenticated.departure'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated.achievements'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisaRoute = AuthenticatedVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUniversitiesRoute =
  AuthenticatedUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScholarshipsRoute =
  AuthenticatedScholarshipsRouteImport.update({
    id: '/scholarships',
    path: '/scholarships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfessorsRoute = AuthenticatedProfessorsRouteImport.update({
  id: '/professors',
  path: '/professors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMissionRoute = AuthenticatedMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIeltsRoute = AuthenticatedIeltsRouteImport.update({
  id: '/ielts',
  path: '/ielts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartureRoute = AuthenticatedDepartureRouteImport.update({
  id: '/departure',
  path: '/departure',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departure': typeof AuthenticatedDepartureRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/ielts': typeof AuthenticatedIeltsRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/mission': typeof AuthenticatedMissionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/professors': typeof AuthenticatedProfessorsRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/universities': typeof AuthenticatedUniversitiesRoute
  '/visa': typeof AuthenticatedVisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departure': typeof AuthenticatedDepartureRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/ielts': typeof AuthenticatedIeltsRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/mission': typeof AuthenticatedMissionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/professors': typeof AuthenticatedProfessorsRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/universities': typeof AuthenticatedUniversitiesRoute
  '/visa': typeof AuthenticatedVisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departure': typeof AuthenticatedDepartureRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/ielts': typeof AuthenticatedIeltsRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/mission': typeof AuthenticatedMissionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/professors': typeof AuthenticatedProfessorsRoute
  '/_authenticated/scholarships': typeof AuthenticatedScholarshipsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/universities': typeof AuthenticatedUniversitiesRoute
  '/_authenticated/visa': typeof AuthenticatedVisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/achievements'
    | '/analytics'
    | '/dashboard'
    | '/departure'
    | '/documents'
    | '/finances'
    | '/ielts'
    | '/mentor'
    | '/mission'
    | '/onboarding'
    | '/professors'
    | '/scholarships'
    | '/settings'
    | '/universities'
    | '/visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/achievements'
    | '/analytics'
    | '/dashboard'
    | '/departure'
    | '/documents'
    | '/finances'
    | '/ielts'
    | '/mentor'
    | '/mission'
    | '/onboarding'
    | '/professors'
    | '/scholarships'
    | '/settings'
    | '/universities'
    | '/visa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/achievements'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/departure'
    | '/_authenticated/documents'
    | '/_authenticated/finances'
    | '/_authenticated/ielts'
    | '/_authenticated/mentor'
    | '/_authenticated/mission'
    | '/_authenticated/onboarding'
    | '/_authenticated/professors'
    | '/_authenticated/scholarships'
    | '/_authenticated/settings'
    | '/_authenticated/universities'
    | '/_authenticated/visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visa': {
      id: '/_authenticated/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof AuthenticatedVisaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/universities': {
      id: '/_authenticated/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof AuthenticatedUniversitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scholarships': {
      id: '/_authenticated/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof AuthenticatedScholarshipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/professors': {
      id: '/_authenticated/professors'
      path: '/professors'
      fullPath: '/professors'
      preLoaderRoute: typeof AuthenticatedProfessorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mission': {
      id: '/_authenticated/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof AuthenticatedMissionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ielts': {
      id: '/_authenticated/ielts'
      path: '/ielts'
      fullPath: '/ielts'
      preLoaderRoute: typeof AuthenticatedIeltsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departure': {
      id: '/_authenticated/departure'
      path: '/departure'
      fullPath: '/departure'
      preLoaderRoute: typeof AuthenticatedDepartureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartureRoute: typeof AuthenticatedDepartureRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedIeltsRoute: typeof AuthenticatedIeltsRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedMissionRoute: typeof AuthenticatedMissionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfessorsRoute: typeof AuthenticatedProfessorsRoute
  AuthenticatedScholarshipsRoute: typeof AuthenticatedScholarshipsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUniversitiesRoute: typeof AuthenticatedUniversitiesRoute
  AuthenticatedVisaRoute: typeof AuthenticatedVisaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartureRoute: AuthenticatedDepartureRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedIeltsRoute: AuthenticatedIeltsRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedMissionRoute: AuthenticatedMissionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfessorsRoute: AuthenticatedProfessorsRoute,
  AuthenticatedScholarshipsRoute: AuthenticatedScholarshipsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUniversitiesRoute: AuthenticatedUniversitiesRoute,
  AuthenticatedVisaRoute: AuthenticatedVisaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
